services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:14-alpine
    container_name: sales_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend NestJS Application
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: sales_backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      # Database connection details
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      # JWT Secret
      JWT_SECRET: ${JWT_SECRET} # Replace with a strong secret in production
    restart: unless-stopped

volumes:
  postgres_data: